export const programmers = [
  {
    id: "f8fff6a6f673b56baa65c656ca9b59b4",
    firstName: "Alexandr",
    lastName: "Hamabrdzumyan",
    phone: "+374 93 11 44 15",
    email: "alexanhambarcumyan@gmail.com",
    education: "Shushi Technology university",
    workExperience: "AIPC",
    trainings: "RELQ school",
    imagePath: "./img/AlexandrHamabrdzumyan.jpg",
  },
  {
    id: "e02b085ccf8db450c6fb02cf03130e41",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "RELQ",
    imagePath: "./img/AniAntonyan.jpg",
  },
  {
    id: "c571462977f6493dcfc8dc5fc3e76a2a",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "+374 98 14 44 50",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
    imagePath: "./img/AnnaHayriyan.jpg",
  },
  {
    id: "e6eee7c86ad4d660f25364ad46a97f39",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: "+374 94 90 21 71",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
    imagePath: "./img/ArmenakQocharyan.jpg",
  },
  {
    id: "ad768a02e16e8e4dce14fc362a4d8f77",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "+374 55 90 01 55",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:
      "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
    imagePath: "./img/ArusyakAghajanyan.jpg",
  },
  {
    id: "94ac1b8adac98761defdfcbfa915184e",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "./img/AfinaPanyan.jpg",
  },
  {
    id: "a897752850270feccdf429b5d76b8e4e",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "+374 93 28 55 95",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "./img/BabkenTadevosyan.jpg",
  },
  {
    id: "d40638a8fff44ba4b2aa0dc313f4e55c",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "+374 99 46 36 23 ",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "./img/HasmikGevorgyan.jpg",
  },
  {
    id: "cc1eaafd60774f1bba7371d538c3b22e",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "./img/HermineMelkumyan.jpg",
  },
  {
    id: "ea6913a3376d210bc3de3acb1480fdc5",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: "+374 97 75 95 99",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
    imagePath: "./img/LarineDanielyan.jpg",
  },
  {
    id: "a0638c496d78d286e114f7640f41b50f",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "+374 91 55 53 74",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
    imagePath: "./img/LianaDashyan.jpg",
  },
  {
    id: "b4e1cf9a0291d9e8a66abe5961e75689",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "+374 43 18 18 34",
    email: "lusineer@gmail.com",
    education: "Economist",
    workExperience: "Municipality",
    trainings: "Relq, MIC",
    imagePath: "./img/LusineYeremyan.jpg",
  },
  {
    id: "ed13f4692cef6425fb4e644fbd1bfccb",
    firstName: "Lusine",
    lastName: "Petrosyan",
    phone: "+374 93 32 29 02",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "notDefined",
    trainings: "Relq",
    imagePath: "./img/LusinePetrosyan.jpg",
  },
  {
    id: "a2a9ef74479801529f81a241d3994a0d",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: "+374 44 05 51 50",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
    imagePath: "./img/MaratHarutyunyan.jpg",
  },
  {
    id: "d7e98c1918850ec9f02f87835c1c64f0",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "+374 94 27 67 00",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
    imagePath: "./img/NarekTovmasyan.jpg",
  },
  {
    id: "ab47ca080f9b3c3bcfb209efc0e48f90",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "+374 98 31 38 71",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "notDefined",
    trainings: "TechBoost4Women,RELQ technology school",
    imagePath: "./img/SedaShahnazaryan.jpg",
  },
  {
    id: "99c9cd8ba0cc3b2cb34459d881da73c4",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "+374 94 24 68 80",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./img/SeryozhaAsatryan.jpg",
  },
  {
    id: "cfbfaf41a92c751be917188ff78b08b9",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "+374 77 12 16 96",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./img/SevakStepanyan.jpg",
  },
  {
    id: "e1efd58ecdf2fba2cd5055ef208825da",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./img/SilvaOhanyan.jpg",
  },
  {
    id: "bd3ccafca23d135eba80e1ad302bbc95",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "./img/SurenGalstyan.jpg",
  },
  {
    id: "aaa41df3f6dea76893639a2ed8f7e546",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "+374 77 15 18 68",
    email: "martirosyant01@mail.ru",
    education: "notDefined",
    workExperience: "notDefined",
    trainings: "Relq School",
    imagePath: "./img/TigranMartirosyan.jpg",
  },
  {
    id: "ac4cb9b271d387d7e0a0b8bc25f7e24e",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "+374 98 156 247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: " ",
    trainings: "RELQ",
    imagePath: "./img/LusineYeremyan.jpg",
  },
  {
    id: "f3b8c8dcb949100fe5247ec8831ddeff",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "+374 44 148 000",
    email: "Khechumyan63@gmail.com",
    education: "YSU",
    workExperience: " ",
    trainings: "RELQ IT school",
    imagePath: "./img/AnahitKhechumyan.jpg",
  },
];
